#! /usr/bin/env python
# -*- coding: utf-8 -*
##########################################################################
# NSAp - Copyright (C) CEA, 2018
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html for details.
##########################################################################

# System import
import os
import argparse
import textwrap
from argparse import RawTextHelpFormatter
from datetime import datetime
from pprint import pprint

# Package import
from pyconnectome import __version__ as version
from pyconnectome.utils.filetools import parse_graph
from pyconnectome.metrics.dfold import convert_folds
from pyconnectome.metrics.dfold import sphere_integration

# Third party import
import json

# Parameters to keep trace
__hopla__ = ["runtime", "inputs", "outputs"]

# Bredala module
try:
    import bredala
    bredala.USE_PROFILER = False
    bredala.register("pyconnectome.utils.filetools",
                     names=["parse_graph"])
    bredala.register("pyconnectome.metrics.dfold",
                     names=["convert_fold", "sphere_integration"])
except:
    pass


# Script documentation
DOC = """
Evaluation of folds features
-----------------------------

Extract features along different folds (e.g : FA) and output a summary of
these features in csv and json files.

Requirements:
    - fold files (.gii) for left and right hemisphere (required).
    - T1 image file (required).
    - scalar image files (e.g FA image file) (required).
    - subject id (required).
    - morphologist graph files (.arg) for left and right hemisphere (required).
    - folds' ids on which to extract features for each hemisphere  : 
      if no fold is specified features are extracted on every folds, 
      if -1 is specified no fold is extracted (optional).
    - white/grey matter segmentation files for left and right hemisphere
      (optional).

Command example on the HCP data :

python pyconnectome_folds_metrics \
    -o $PROJECT/HCP_FOLDS/TEST_OUTPUT \
    -s 101006 \
    -p /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/folds/3.1/default_session_auto/L101006_default_session_auto.data/aims_Tmtktri.gii \
       /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/folds/3.1/default_session_auto/R101006_default_session_auto.data/aims_Tmtktri.gii \
    -t /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/101006.nii.gz \
    -a $PROJECT/HCP_FOLDS/TEST_OUTPUT/101006/3000/dtifit_FA.nii.gz \
    -g /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/folds/3.1/default_session_auto/L101006_default_session_auto.arg \
       /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/folds/3.1/default_session_auto/R101006_default_session_auto.arg \
    -m /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/segmentation/Lgrey_white_101006.nii.gz \
       /neurospin/hcp/ANALYSIS/3T_morphologist/101006/t1mri/default_acquisition/default_analysis/segmentation/Rgrey_white_101006.nii.gz \
    -l 86 \
    -r 86

"""


def is_file(filepath):
    """ Check file's existence - argparse 'type' argument.
    """
    if not os.path.isfile(filepath):
        raise argparse.ArgumentError("File does not exist: %s" % filepath)
    return filepath


def is_directory(dirarg):
    """ Type for argparse - checks that directory exists.
    """
    if not os.path.isdir(dirarg):
        raise argparse.ArgumentError(
            "The directory '{0}' does not exist!".format(dirarg))
    return dirarg


# Parse input arguments
def get_cmd_line_args():
    """
    Create a command line argument parser and return a dict mapping
    <argument name> -> <argument value>.
    """
    parser = argparse.ArgumentParser(
        prog="python pyconnectome_get_folds_metrics",
        description=textwrap.dedent(DOC),
        formatter_class=RawTextHelpFormatter)

    # Required arguments
    required = parser.add_argument_group("required arguments")
    required.add_argument(
        "-o", "--outdir",
        type=is_directory, required=True, metavar="<path>",
        help="Directory where to output.")
    required.add_argument(
        "-s", "--subject", type=str, required=True, help="Subject ID.")
    required.add_argument(
        "-p", "--foldsfile",
        type=is_file, nargs='+', required=True, metavar="<path>",
        help="Path to the folds .gii file.")
    required.add_argument(
        "-t", "--t1",
        type=is_file, required=True, metavar="<path>",
        help="Path to the T1 image file.")
    required.add_argument(
        "-a", "--scalarfile",
        type=is_file, nargs='+', required=True, metavar="<path>",
        help="Path to at least one scalar image file.")
    required.add_argument(
        "-g", "--graphfile",
        type=is_file, nargs='+', required=True, metavar="<path>",
        help="Path to the morphologist graph file.")

    # Optional argument
    parser.add_argument(
        "-l", "--leftfolds",
        type=int, nargs='*',
        help="Selection of left hemisphere folds indexes on which to compute \
             value (e.g : 94). Not adding this argument will compute the \
             folds' metrics on every fold and putting this argument to -1 \
             won't compute any value for the hemisphere folds.")
    parser.add_argument(
        "-r", "--rightfolds",
        type=int, nargs='*',
        help="Selection of right hemisphere folds indexes on which to compute \
             value (e.g : 94). Not adding this argument will compute the \
             folds' metrics on every fold and putting this argument to -1 \
             won't compute any value for the hemisphere folds.")
    parser.add_argument(
        "-m", "--wgmfile",
        type=is_file, nargs='*', metavar="<path>",
        help="Path to the white/grey matter segmentation files (one for each"
              "hemisphere).")
    parser.add_argument(
        "-v", "--verbose",
        type=int, choices=[0, 1, 2], default=2,
        help="Increase the verbosity level: 0 silent, [1, 2] verbose.")

    # Create a dict of arguments to pass to the 'main' function
    args = parser.parse_args()
    kwargs = vars(args)
    verbose = kwargs.pop("verbose")
    return kwargs, verbose

"""
Parse the command line.
"""
inputs, verbose = get_cmd_line_args()
tool = "pyconnectome_get_folds_metrics"
timestamp = datetime.now().isoformat()
tool_version = version
params = locals()
runtime = dict([(name, params[name])
               for name in ("tool", "tool_version",
                            "timestamp")])
outputs = None
if verbose > 0:
    pprint("[info] Starting computation of folds metrics...")
    pprint("[info] Runtime:")
    pprint(runtime)
    pprint("[info] Inputs:")
    pprint(inputs)

"""
Start the folds' metrics computation
"""

# Parse the Morphologist graph file to get the fold labels
labelsL = parse_graph(inputs["graphfile"][0])
labelsR = parse_graph(inputs["graphfile"][1])

# Convert the folds in physical morphological space to NIFTI voxel space
foldsL = convert_folds(inputs["foldsfile"][0], inputs["graphfile"][0],
                       inputs["t1"])
foldsR = convert_folds(inputs["foldsfile"][1], inputs["graphfile"][1],
                       inputs["t1"])
foldsL_ = {}
foldsR_ = {}

# If no folds were specified, select all folds for the computation
if inputs["leftfolds"] is None:
    for ind in labelsL.keys():
        foldsL_[ind] = foldsL[ind]
# If the user specified folds (-1 == no folds), add them to computed on
elif inputs["leftfolds"][0] != -1:
    for ind in inputs["leftfolds"]:
        foldsL_[ind] = foldsL[ind]

if inputs["rightfolds"] is None:
    for ind in labelsR.keys():
        foldsR_[ind] = foldsR[ind]
elif inputs["rightfolds"][0] != -1:
    for ind in inputs["rightfolds"]:
        foldsR_[ind] = foldsR[ind]

if foldsL_:
    measuresL = sphere_integration(inputs["t1"], foldsL_, inputs["scalarfile"],
                                   m_file=inputs["wgmfile"][0], radius=2)
if foldsR_:
    measuresR = sphere_integration(inputs["t1"], foldsR_, inputs["scalarfile"],
                                   m_file=inputs["wgmfile"][1], radius=2)

"""
Save output in json and csv files
"""

# Write JSON output
if foldsL_:
    out_file = os.path.join(inputs["outdir"],
                            "Lh_{0}_folds_measure.json".format(
                            inputs["subject"]))
    with open(out_file, 'w') as outfile:
        json.dump(measuresL, outfile)
if foldsR_:
    out_file = os.path.join(inputs["outdir"],
                            "Rh_{0}_folds_measure.json".format(
                            inputs["subject"]))
    with open(out_file, 'w') as outfile:
        json.dump(measuresR, outfile)

# Write csv output
if foldsL_:
    out_file = os.path.join(inputs["outdir"],
                            "Lh_{0}_folds_measure.csv".format(
                            inputs["subject"]))
    with open(out_file, 'w') as f:
        random_fold = measuresL.keys()[0]
        random_point = measuresL[random_fold].keys()[0]
        features = []
        header = "Fold;PointCoord"
        for feat in measuresL[random_fold][random_point].keys():
            features.append(feat)
            for value in measuresL[random_fold][random_point][feat].keys():
                header = "{0};{1}_{2}".format(header, feat, value)
        f.write(header)
        f.write("\n")

        for fold in measuresL.keys():
            for point in measuresL[fold].keys():
                line = "{0};{1}".format(labelsL[fold], point)
                for feat in features:
                    for value in measuresL[fold][point][feat].keys():
                        line = "{0};{1}".format(line,
                               measuresL[fold][point][feat][value])
                f.write(line)
                f.write("\n")

if foldsR_:
    out_file = os.path.join(inputs["outdir"],
                            "Rh_{0}_folds_measure.csv".format(
                            inputs["subject"]))
    with open(out_file, 'w') as f:
        random_fold = measuresR.keys()[0]
        random_point = measuresR[random_fold].keys()[0]
        features = []
        header = "Fold;PointCoord"
        for feat in measuresR[random_fold][random_point].keys():
            features.append(feat)
            for value in measuresR[random_fold][random_point][feat].keys():
                header = "{0};{1}_{2}".format(header, feat, value)
        f.write(header)
        f.write("\n")

        for fold in measuresR.keys():
            for point in measuresR[fold].keys():
                line = "{0};{1}".format(labelsR[fold], point)
                for feat in features:
                    for value in measuresR[fold][point][feat].keys():
                        line = "{0};{1}".format(line,
                                measuresR[fold][point][feat][value])
                f.write(line)
                f.write("\n")
